#!/usr/bin/env python3
"""
build.py — generate the RH56DFTP tactile frames and expand the hand xacro to
plain URDF, with NO ROS / xacro dependency.

Why this exists
---------------
rh56dftp_description is a framework-agnostic hand description (consumed by
Pinocchio / MuJoCo / RViz). The kinematic macro urdf/rh56dftp_macro.xacro uses
only a tiny, closed subset of xacro:
    * ${prefix}, ${side}, ${mesh_root|mesh_visual|mesh_collision} substitution
    * <xacro:if value="${side == 'left'}"> / '${side == 'right'}'> blocks
    * 3 <xacro:property> definitions
That subset is expanded here directly, so a plain URDF can be produced on any
machine without installing ROS or the xacro package.

Single source of truth
-----------------------
tactile/tactile_layout.yaml drives BOTH generated artifacts:
    * urdf/tactile_frames.xacro   (a fixed frame per tactile region, for RViz/xacro)
    * the tactile frames appended to the expanded plain URDFs

Commands
--------
    build.py --check                 validate tactile_layout.yaml totals only
    build.py frames                  (re)generate urdf/tactile_frames.xacro
    build.py expand                  (re)generate urdf/rh56dftp_{left,right}.urdf
    build.py all                     frames + expand (default)

Options
-------
    --mesh-root PATH   mesh directory root used in the expanded URDFs, minus the
                       /<side> suffix. Default "../meshes" -> ../meshes/left/...
                       Use "package://rh56dftp_description/meshes" for ROS.
"""
from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import yaml

PKG = Path(__file__).resolve().parent.parent
MACRO = PKG / "urdf" / "rh56dftp_macro.xacro"
LAYOUT = PKG / "tactile" / "tactile_layout.yaml"
PAD_GEOMETRY = PKG / "tactile" / "pad_geometry.yaml"
FRAMES_XACRO = PKG / "urdf" / "tactile_frames.xacro"

SIDES = ("left", "right")
GENERATED_BANNER = "GENERATED by tools/build.py from tactile/tactile_layout.yaml — DO NOT EDIT BY HAND"


# --------------------------------------------------------------------------- #
# tactile layout
# --------------------------------------------------------------------------- #
def load_layout() -> dict:
    with open(LAYOUT) as fh:
        return yaml.safe_load(fh)


def check_layout(layout: dict) -> None:
    """Fail loudly if the declared totals disagree with the region entries."""
    regions = layout["regions"]
    n_regions = len(regions)
    n_taxels = sum(r["taxels"] for r in regions.values())
    for key, r in regions.items():
        rows, cols = r["grid"]
        if rows * cols != r["taxels"]:
            raise SystemExit(f"[build] region '{key}': grid {rows}x{cols} != taxels {r['taxels']}")
    declared = layout["totals"]
    if declared["regions"] != n_regions or declared["taxels"] != n_taxels:
        raise SystemExit(
            f"[build] totals mismatch: declared regions={declared['regions']} taxels={declared['taxels']}, "
            f"actual regions={n_regions} taxels={n_taxels}"
        )
    print(f"[build] tactile_layout.yaml OK — {n_regions} regions, {n_taxels} taxels")


def load_pad_geometry() -> dict:
    """Per-region, per-side pad pose (xyz/rpy in the parent frame), or {} if absent.

    Generated by tools/estimate_tactile_frames.py. When missing, frames fall back
    to the origin (xyz 0 0 0, rpy 0 0 0) — the old 'nominal' placement.
    """
    if not PAD_GEOMETRY.exists():
        print(f"[build] {PAD_GEOMETRY.name} not found — tactile frames use nominal (origin) placement")
        return {}
    with open(PAD_GEOMETRY) as fh:
        return yaml.safe_load(fh).get("regions", {})


def _origin_xml(geom: dict, region: str, side: str) -> str:
    """<origin> for one region on one side, from pad_geometry (else zeros)."""
    pose = geom.get(region, {}).get("pose", {}).get(side)
    if not pose:
        return '<origin xyz="0 0 0" rpy="0 0 0"/>'
    xyz = " ".join(f"{v:.6g}" for v in pose["xyz"])
    rpy = " ".join(f"{v:.6g}" for v in pose["rpy"])
    return f'<origin xyz="{xyz}" rpy="{rpy}"/>'


def tactile_frame_elements(layout: dict, geom: dict, prefix: str, indent: str = "  ", side: str | None = None) -> str:
    """Return URDF <link>/<joint> XML for every tactile region.

    side=None (xacro macro): the pose differs per hand, so emit both sides guarded
        by <xacro:if value="${side == '...'}"> — the macro takes a `side` param.
    side='left'/'right' (expanded plain URDF): emit the concrete pose directly.
    """
    fs = layout.get("frame_suffix", "_touch")
    out = []
    for key, r in layout["regions"].items():
        frame = f"{prefix}{key}{fs}"
        parent = f"{prefix}{r['parent_link']}"
        rows, cols = r["grid"]
        if side is None:
            origin = (
                f'{indent}  <xacro:if value="${{side == \'left\'}}">{_origin_xml(geom, key, "left")}</xacro:if>\n'
                f'{indent}  <xacro:if value="${{side == \'right\'}}">{_origin_xml(geom, key, "right")}</xacro:if>\n'
            )
        else:
            origin = f'{indent}  {_origin_xml(geom, key, side)}\n'
        out.append(
            f'{indent}<!-- {key}: dds={r["dds_field"]} grid={rows}x{cols} '
            f'({r["taxels"]} taxels) modbus={r["modbus_addr"]} -->\n'
            f'{indent}<link name="{frame}"/>\n'
            f'{indent}<joint name="{frame}_joint" type="fixed">\n'
            f'{indent}  <parent link="{parent}"/>\n'
            f'{indent}  <child link="{frame}"/>\n'
            f"{origin}"
            f'{indent}</joint>'
        )
    return "\n".join(out)


def generate_frames_xacro(layout: dict, geom: dict) -> None:
    body = tactile_frame_elements(layout, geom, prefix="${prefix}", indent="    ", side=None)
    text = (
        '<?xml version="1.0"?>\n'
        f"<!-- {GENERATED_BANNER} -->\n"
        '<robot xmlns:xacro="http://www.ros.org/wiki/xacro">\n'
        '  <xacro:macro name="rh56dftp_tactile_frames" params="prefix side">\n'
        f"{body}\n"
        "  </xacro:macro>\n"
        "</robot>\n"
    )
    FRAMES_XACRO.write_text(text)
    print(f"[build] wrote {FRAMES_XACRO.relative_to(PKG)} ({len(layout['regions'])} frames)")


# --------------------------------------------------------------------------- #
# minimal xacro expander (closed subset — see module docstring)
# --------------------------------------------------------------------------- #
_MACRO_RE = re.compile(
    r'<xacro:macro\s+name="rh56dftp_hand"[^>]*>(?P<body>.*)</xacro:macro>', re.DOTALL
)
_PROPERTY_RE = re.compile(r"<xacro:property\b.*?/>", re.DOTALL)
_IF_TOKEN_RE = re.compile(r'<xacro:if\s+value="([^"]*)">|</xacro:if>', re.DOTALL)


def _eval_side_cond(cond: str, side: str) -> bool:
    c = cond.strip()
    if c.startswith("${") and c.endswith("}"):
        c = c[2:-1].strip()
    m = re.fullmatch(r"side\s*==\s*'(\w+)'", c)
    if not m:
        raise SystemExit(f"[build] unsupported xacro:if condition (expander is intentionally minimal): {cond!r}")
    return m.group(1) == side


def _resolve_ifs(text: str, side: str) -> str:
    """Keep/drop <xacro:if value="${side == '...'}"> blocks for the target side."""
    out: list[str] = []
    keep_stack = [True]
    pos = 0
    for m in _IF_TOKEN_RE.finditer(text):
        if all(keep_stack):
            out.append(text[pos:m.start()])
        pos = m.end()
        if m.group(0).startswith("<xacro:if"):
            keep_stack.append(_eval_side_cond(m.group(1), side))
        else:
            if len(keep_stack) == 1:
                raise SystemExit("[build] unbalanced </xacro:if> in macro")
            keep_stack.pop()
    if len(keep_stack) != 1:
        raise SystemExit("[build] unclosed <xacro:if> in macro")
    out.append(text[pos:])
    return "".join(out)


def expand_side(macro_text: str, layout: dict, geom: dict, side: str, mesh_root_base: str) -> str:
    m = _MACRO_RE.search(macro_text)
    if not m:
        raise SystemExit("[build] could not locate <xacro:macro name=\"rh56dftp_hand\"> in macro file")
    body = m.group("body")

    # 1. drop property declarations (values are recomputed below)
    body = _PROPERTY_RE.sub("", body)
    # 2. resolve side conditionals BEFORE any ${...} substitution
    body = _resolve_ifs(body, side)
    # 3. substitute properties + prefix/side (distinct literal tokens, no overlap)
    prefix = f"{side}_"
    mesh_root = f"{mesh_root_base}/{side}"
    subs = {
        "${mesh_visual}": f"{mesh_root}/visual",
        "${mesh_collision}": f"{mesh_root}/collision",
        "${mesh_root}": mesh_root,
        "${prefix}": prefix,
        "${side}": side,
    }
    for tok, val in subs.items():
        body = body.replace(tok, val)

    leftover = re.findall(r"\$\{[^}]*\}|<xacro:[a-z_]+", body)
    if leftover:
        raise SystemExit(f"[build] unexpanded tokens remain for side={side}: {sorted(set(leftover))[:8]}")

    tactile = tactile_frame_elements(layout, geom, prefix=prefix, indent="  ", side=side)
    robot = (
        '<?xml version="1.0"?>\n'
        f"<!-- {GENERATED_BANNER} (run: tools/build.py expand) -->\n"
        f'<robot name="rh56dftp_{side}">\n'
        f"{body}\n"
        "  <!-- ===== tactile skin frames (from tactile/tactile_layout.yaml) ===== -->\n"
        f"{tactile}\n"
        "</robot>\n"
    )
    ET.fromstring(robot)  # parse-check; raises on malformed XML
    return robot


def generate_urdfs(layout: dict, geom: dict, mesh_root_base: str) -> None:
    macro_text = MACRO.read_text()
    for side in SIDES:
        urdf = expand_side(macro_text, layout, geom, side, mesh_root_base)
        out = PKG / "urdf" / f"rh56dftp_{side}.urdf"
        out.write_text(urdf)
        root = ET.fromstring(urdf)
        n_links = len(root.findall("link"))
        n_joints = len(root.findall("joint"))
        print(f"[build] wrote {out.relative_to(PKG)} — {n_links} links, {n_joints} joints")


# --------------------------------------------------------------------------- #
def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", nargs="?", default="all", choices=["all", "frames", "expand", "--check"])
    ap.add_argument("--check", dest="check_flag", action="store_true", help="validate layout totals and exit")
    ap.add_argument("--mesh-root", default="../meshes",
                    help='mesh root minus /<side> (default "../meshes"; use package://... for ROS)')
    args = ap.parse_args()

    layout = load_layout()
    check_layout(layout)  # always validate first
    if args.check_flag or args.command == "--check":
        return

    geom = load_pad_geometry()
    if args.command in ("frames", "all"):
        generate_frames_xacro(layout, geom)
    if args.command in ("expand", "all"):
        generate_urdfs(layout, geom, args.mesh_root)


if __name__ == "__main__":
    sys.exit(main())
