#!/usr/bin/env python3
"""Estimate tactile pad frames (pose + footprint) from the hand meshes.

Writes tactile/pad_geometry.yaml (GENERATED), consumed by:
  * tools/build.py           -> <origin> of each <region>_touch fixed joint
  * inspire_hand_bridge cloud -> per-region grid pitch (real pad size, not a
                                 single global guess)

Why this exists
---------------
The tactile_layout.yaml placement is "nominal": every _touch frame would sit at
its parent link origin (the joint axis, inside the finger) with identity
orientation, and the point cloud used one global 2.5 mm pitch. That put the
panels neither on the pad surface, nor parallel to it, nor at the right size.

Here we derive, per region and per side, from the visual meshes:
  * the pad SURFACE center and orientation (grid X = finger length, Y = width,
    Z = outward surface normal), expressed in the PARENT link frame;
  * the pad FOOTPRINT (u, v) in metres, so the grid pitch is size/(n-1).

Method (see the two mesh classes of pad):
  * Fingertip / palm pads are near-flat plates -> plane by PCA of the pad mesh.
  * Finger phalanx cushions (rubber_N) wrap the whole segment -> the palmar
    direction is taken GLOBALLY from the palm's outward normal (a clean plane),
    projected into the parent frame; only the palmar cap of the cushion is kept.

This is an approximation of a curved rubber surface by a flat grid: expect
sub-mm error on tips/tops and up to a few mm on the wrap-around palm cushions.
Good enough to visualise pressure on the mesh; re-run if the meshes change:

    python3 tools/estimate_tactile_frames.py
"""
from __future__ import annotations

import math
import struct
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np
import yaml

PKG = Path(__file__).resolve().parent.parent
LAYOUT = PKG / "tactile" / "tactile_layout.yaml"
OUT = PKG / "tactile" / "pad_geometry.yaml"
SIDES = ("left", "right")
BANNER = "GENERATED by tools/estimate_tactile_frames.py from the visual meshes — DO NOT EDIT BY HAND"


# --------------------------------------------------------------------------- #
# minimal STL reader (binary + ASCII), no external dependency
# --------------------------------------------------------------------------- #
def load_stl(path: Path) -> np.ndarray:
    b = path.read_bytes()
    if b[:5].lstrip().lower().startswith(b"solid") and b"facet" in b[:2048].lower():
        verts = [
            [float(s[1]), float(s[2]), float(s[3])]
            for s in (line.split() for line in b.decode("latin1").splitlines())
            if len(s) == 4 and s[0] == "vertex"
        ]
        return np.array(verts)
    n = struct.unpack("<I", b[80:84])[0]
    v = np.empty((n * 3, 3))
    off = 84
    for i in range(n):
        vals = struct.unpack("<12f", b[off:off + 48])
        v[3 * i:3 * i + 3] = np.array(vals[3:12]).reshape(3, 3)
        off += 50
    return v


# --------------------------------------------------------------------------- #
# rotation helpers (URDF fixed-axis roll-pitch-yaw)
# --------------------------------------------------------------------------- #
def R_to_rpy(R: np.ndarray) -> tuple[float, float, float]:
    p = math.atan2(-R[2, 0], math.hypot(R[0, 0], R[1, 0]))
    y = math.atan2(R[1, 0], R[0, 0])
    r = math.atan2(R[2, 1], R[2, 2])
    return r, p, y


def rpy_to_R(r: float, p: float, y: float) -> np.ndarray:
    cr, sr, cp, sp, cy, sy = math.cos(r), math.sin(r), math.cos(p), math.sin(p), math.cos(y), math.sin(y)
    return np.array([
        [cy * cp, cy * sp * sr - sy * cr, cy * sp * cr + sy * sr],
        [sy * cp, sy * sp * sr + cy * cr, sy * sp * cr - cy * sr],
        [-sp, cp * sr, cp * cr],
    ])


# --------------------------------------------------------------------------- #
class Hand:
    """One side's kinematics + visual meshes, with zero-config FK."""

    def __init__(self, side: str):
        self.side = side
        self.prefix = f"{side}_"
        self.mesh_dir = PKG / "meshes" / side / "visual"
        root = ET.parse(PKG / "urdf" / f"rh56dftp_{side}.urdf").getroot()
        self.vis: dict[str, str] = {}
        self.child: dict[str, tuple[str, np.ndarray]] = {}
        self.kids: dict[str, list[str]] = {}
        for link in root.iter("link"):
            m = link.find("visual/geometry/mesh")
            if m is not None:
                self.vis[link.get("name")] = m.get("filename").split("/")[-1]
        for j in root.iter("joint"):
            p, c, o = j.find("parent").get("link"), j.find("child").get("link"), j.find("origin")
            xyz = np.array([float(x) for x in (o.get("xyz").split() if o is not None and o.get("xyz") else [0, 0, 0])])
            rpy = [float(x) for x in (o.get("rpy").split() if o is not None and o.get("rpy") else [0, 0, 0])]
            T = np.eye(4); T[:3, :3] = rpy_to_R(*rpy); T[:3, 3] = xyz
            self.child[c] = (p, T)
            self.kids.setdefault(p, []).append(c)

    def fk(self, link: str) -> np.ndarray:
        T, cur = np.eye(4), link
        while cur in self.child:
            p, Tj = self.child[cur]
            T = Tj @ T
            cur = p
        return T

    def mesh(self, link: str, n: int = 4000) -> np.ndarray | None:
        fn = self.vis.get(link)
        if not fn:
            return None
        v = load_stl(self.mesh_dir / fn)
        if len(v) > n:
            v = v[np.random.default_rng(0).choice(len(v), n, replace=False)]
        return v

    def rubber_child(self, parent: str) -> str | None:
        return next((c for c in self.kids.get(parent, []) if "rubber" in c), None)

    def pad_child(self, rubber_link: str) -> str | None:
        return next((c for c in self.kids.get(rubber_link, []) if c.endswith("_pad")), None)

    def palm_normal_root(self) -> np.ndarray:
        """Outward palm normal (away from the back of the hand), in the root frame.

        The palm mesh's own link origin is NOT a reliable "inside" reference (it
        can sit anywhere relative to the mesh, e.g. offset mostly in Z while the
        normal is mostly X — comparing against it is comparing near-orthogonal
        vectors, i.e. noise). Use the wrist/hand_base centroid instead: it is
        unambiguously on the dorsal (back) side, so palm_centroid - back_centroid
        points outward/palmar by construction.
        """
        pts = self.mesh(f"{self.prefix}palm")
        T = self.fk(f"{self.prefix}palm")
        w = (T[:3, :3] @ pts.T).T + T[:3, 3]
        c = w.mean(0)
        _, V = np.linalg.eigh((w - c).T @ (w - c))
        n = V[:, 0] / np.linalg.norm(V[:, 0])

        back_pts = self.mesh(f"{self.prefix}hand_base")
        T_back = self.fk(f"{self.prefix}hand_base")
        back_c = (T_back[:3, :3] @ back_pts.T).T.mean(0) + T_back[:3, 3]
        return n if n @ (c - back_c) > 0 else -n


def _pad_ground_truth_dir(hand: Hand, parent: str, rc: str, L_root: np.ndarray) -> np.ndarray | None:
    """Outward direction (root frame, perp. to the finger axis) from a *_pad
    mesh, when the cushion has one as a child (fingertip-adjacent phalanges
    only). This is a real fingerprint/grip patch glued to the palmar face by
    the hand's own design — the most reliable palmar reference available,
    more reliable than any direction derived from the flat palm plate (see
    estimate_region docstring: that projection can flip sign on segments whose
    long axis diverges a lot from the palm's, e.g. the thumb).
    """
    pad_link = hand.pad_child(rc)
    if pad_link is None:
        return None
    T_pr = hand.fk(parent)
    T_pad = hand.fk(pad_link)
    pad_c_root = (T_pad[:3, :3] @ hand.mesh(pad_link).T).T.mean(0) + T_pad[:3, 3]
    cushion_c_root = (T_pr[:3, :3] @ hand.mesh(rc).T).T.mean(0) + T_pr[:3, 3]
    diff = pad_c_root - cushion_c_root
    diff_perp = diff - (diff @ L_root) * L_root
    norm = np.linalg.norm(diff_perp)
    return diff_perp / norm if norm > 1e-9 else None


def estimate_region(
    hand: Hand, name: str, spec: dict, palm_n_root: np.ndarray, finger_n_root: dict[str, np.ndarray]
) -> dict:
    """finger_n_root: {finger_name: last computed n in root frame for that finger},
    filled in as regions are processed (dict order in tactile_layout.yaml puts
    *_tip/*_top before *_palm/*_middle for every finger) — used to keep a
    proximal segment's palmar side consistent with its own finger's distal one,
    instead of the global (and, for the thumb, unreliable) palm normal.
    """
    finger = name.split("_")[0]  # region names are '<finger>_<part>'
    parent = f"{hand.prefix}{spec['parent_link']}"
    rc = hand.rubber_child(parent)
    if rc is not None:
        _, Tj = hand.child[rc]
        pad = (Tj[:3, :3] @ hand.mesh(rc).T).T + Tj[:3, 3]   # cushion in parent frame
        phal = hand.mesh(parent)
        curved = True
    else:
        pad = hand.mesh(parent)                              # tip / palm own plate
        phal = pad
        curved = False

    _, Vp = np.linalg.eigh((phal - phal.mean(0)).T @ (phal - phal.mean(0)))
    L = Vp[:, -1] / np.linalg.norm(Vp[:, -1])                # finger long axis (unsigned PCA)
    T_pr = hand.fk(parent)

    # A PCA eigenvector has no inherent sign: fix L to point proximal->distal
    # (wrist/palm -> fingertip) using the kinematic chain itself as ground
    # truth, so the grid's row axis (baked as local X in the _touch frame) is
    # consistently oriented across all regions/fingers. Every region's parent
    # link has a kinematic grandparent further up the chain (via its fixed
    # 'rubber_N' joint for *_tip regions) that is unambiguously more proximal.
    if parent in hand.child:
        grandparent, _ = hand.child[parent]
        bone_dir = T_pr[:3, 3] - hand.fk(grandparent)[:3, 3]
        L_root_unsigned = T_pr[:3, :3] @ L
        if L_root_unsigned @ bone_dir < 0:
            L = -L

    L_root = T_pr[:3, :3] @ L
    palm_par = T_pr[:3, :3].T @ palm_n_root                  # palmar dir in parent frame

    if curved:
        n = palm_par - (palm_par @ L) * L
        n /= np.linalg.norm(n)
        n_root = T_pr[:3, :3] @ n

        # Prefer a reliable local reference over the global palm direction:
        # 1) this segment's own *_pad mesh, if it has one (fingertip phalanges);
        # 2) else, the already-resolved sibling segment on the SAME finger
        #    (proximal phalanges have no _pad, but must face the same way as
        #    their finger's distal phalanx).
        gt = _pad_ground_truth_dir(hand, parent, rc, L_root)
        if gt is None:
            gt = finger_n_root.get(finger)  # already-resolved sibling on same finger
        if gt is not None and n_root @ gt < 0:
            n = -n
            n_root = -n_root
        finger_n_root[finger] = n_root

        proj = (pad - phal.mean(0)) @ n
        cap = pad[proj > np.percentile(proj, 70)]           # palmar cap of the sleeve
        pad_sel = cap if len(cap) > 30 else pad
    else:
        _, Vq = np.linalg.eigh((pad - pad.mean(0)).T @ (pad - pad.mean(0)))
        n = Vq[:, 0] / np.linalg.norm(Vq[:, 0])
        L = Vq[:, -1] / np.linalg.norm(Vq[:, -1])
        if (T_pr[:3, :3] @ n) @ palm_n_root < 0:
            n = -n
        # This flat-plate L is its own fresh (unsigned) PCA axis, distinct from
        # the one fixed above — re-apply the same proximal->distal sign fix.
        if parent in hand.child:
            grandparent, _ = hand.child[parent]
            bone_dir = T_pr[:3, 3] - hand.fk(grandparent)[:3, 3]
            if (T_pr[:3, :3] @ L) @ bone_dir < 0:
                L = -L
        pad_sel = pad

    u = L - (L @ n) * n; u /= np.linalg.norm(u)
    v = np.cross(n, u); v /= np.linalg.norm(v)
    c = pad_sel.mean(0)
    su = float(np.percentile((pad_sel - c) @ u, 95) - np.percentile((pad_sel - c) @ u, 5))
    sv = float(np.percentile((pad_sel - c) @ v, 95) - np.percentile((pad_sel - c) @ v, 5))
    rpy = R_to_rpy(np.column_stack([u, v, n]))
    return {"xyz": [round(float(x), 6) for x in c], "rpy": [round(float(x), 6) for x in rpy],
            "size_m": [round(su, 6), round(sv, 6)]}


def main() -> None:
    layout = yaml.safe_load(open(LAYOUT))
    hands = {s: Hand(s) for s in SIDES}
    palm_n = {s: hands[s].palm_normal_root() for s in SIDES}
    finger_n_root: dict[str, dict[str, np.ndarray]] = {s: {} for s in SIDES}

    regions: dict[str, dict] = {}
    for name, spec in layout["regions"].items():
        per_side = {s: estimate_region(hands[s], name, spec, palm_n[s], finger_n_root[s]) for s in SIDES}
        # footprint size is mirror-invariant; keep one copy, pose is per-side.
        size = per_side["left"]["size_m"]
        regions[name] = {
            "size_m": size,
            "pose": {s: {"xyz": per_side[s]["xyz"], "rpy": per_side[s]["rpy"]} for s in SIDES},
        }

    with open(OUT, "w") as f:
        f.write(f"# {BANNER}\n")
        f.write("# Poses are per side (xyz m, rpy rad) in the PARENT link frame; regenerate after mesh changes.\n")
        yaml.safe_dump({"regions": regions}, f, sort_keys=False, default_flow_style=None)
    print(f"[estimate] wrote {OUT.relative_to(PKG)} — {len(regions)} regions x {len(SIDES)} sides")
    for name, r in regions.items():
        su, sv = r["size_m"]
        print(f"  {name:14s} size {su * 1000:6.1f} x {sv * 1000:5.1f} mm")


if __name__ == "__main__":
    sys.exit(main())
